### ISSUE TITLE
Support `.env` files

### ISSUE THREAD

**Issue by markbates** [gobuffalo/envy#2]
https://github.com/gobuffalo/buffalo/issues/516

It would be great if envy loaded .env files if they exist.

**Comment by dexafree** [comment]
I propose using [this library](https://github.com/joho/godotenv/) and exposing an `envy.Reload()` function that reloads the environment variables (as the `map[string]string` containing the variables is loaded at the start of the program, and thus if an external library is used to populate ENV, it won't be noticed by envy).

Also, if that is made, a great way of integrating it to buffalo would be allowing env overriding by `GO_ENV`:

* Common ENV settings (such as port, app name...): `.env`
* Environment dependant settings (ie: SMTP_USER): `.env.development`, `.env.production`, `.env.test`

That would allow overriding if needed (I assume that by using the library and passing the files in the correct order, the correct values will be set).

**Comment by markbates** [comment]
I would be open to a PR for this.

-----------
Mark Bates
