### ISSUE TITLE
Unknown import path in envy.go file

### ISSUE THREAD

**Issue by mychell** [gobuffalo/envy#22]
go mod encounters an error when trying to load one of the packages. I think the package location (`"github.com/rogpeppe/go-internal/modfile"`) might have been moved.

```
go: finding github.com/rogpeppe/go-internal/modfile latest
```

```
../../../go/pkg/mod/github.com/gobuffalo/envy@v1.6.12/envy.go:26:2: unknown import path "github.com/rogpeppe/go-internal/modfile": cannot find module providing package github.com/rogpeppe/go-internal/modfile
```

**Comment by stanislas-m** [comment]
Please try again with the latest released version, and reopen this issue if you still have the same problem.
