### ISSUE TITLE
Open to new convenience functions?

### ISSUE THREAD

**Issue by fillup** [gobuffalo/envy#27]
Hi there - 

In using `envy` I've run into a common issue when using environment variables: they can only hold strings, but sometimes a specific data type is needed. To address that we wrote a library, https://github.com/silinternational/php-env for PHP, with some handy methods like `getArray` as well as overloading the `get` method to parse out booleans properly.  I'd like similar capabilities in Go, but before I write my own package I wanted to ask if you'd be open to some new functions being added to `envy`, for example I'd like to add:

```go
// GetBool and MustGetBool will match the env string value for variations of "true" and return true, otherwise false
func GetBool(key string, default bool) bool {...}
func MustGetBool(key string) (bool, error) {...}

// GetArrayStrings and MustGetArrayStrings will split env string value by a delimiter and return as array of strings
func GetArrayStrings(key string, default []string) []string {...}
func MustGetArrayStrings(key string) ([]string, error) {...}
```

If you're open to these features being added I'll happily submit a PR with them for your review. 

Thanks,
Phillip

**Comment by markbates** [comment]
Sorry, but I'm going to say no. First, this once simple package is already too bloated, and it's scope too large.

I'm considering what a v2 would look like, and in that world, these sorts of the functions would be the purpose of that package.

**Comment by fillup** [comment]
No worries, I understand the challenges of maintaining an open source project which is why I asked first :-)
