### ISSUE TITLE
Envy Breaks Packr2 GoMod=off

### ISSUE THREAD

**Issue by esinek** [gobuffalo/envy#34]
our project is not using modules (one of the packages prevents this so we currently can't migrate to modules). As a result we have modules turned off.
As part of our build/deployment we go get packr2 (which pulls in envy). The latest release of envy always assumes modules is turned on and therefore our packr2 command fails with

`Error: go.mod cannot be read or does not exist while go module is enabled`

Since I can't specify a version when using go get, I am hoping there is an alternate way to get the previous version that supports non-modules.

**Comment by markbates** [comment]
Unfortunately we had to make this breaking change to better support modules. Non of the Buffalo projects support GOPATH anymore, sorry. 

My recommendations, apart from move to modules, would be to vendor your dependencies or use something like dep to manage them. 

Sorry.
