### ISSUE TITLE
Feature Request - add docker swarm secret  support

### ISSUE THREAD

**Issue by rpwatkins** [gobuffalo/envy#35]
I would like to augment Envy so that it can retrieve secrets created in a Docker swarm. It would not be difficult and I am happy to write a pull request with the code. But before I do, I thought I'd checkin here to see if there is any interest in the proposal.
Cheers,
Rod

**Comment by sio4** [comment]
Outdated, but I would love to hear what is the details of your proposal.

I am currently considering cleaning the module and the direction will be "simple and straightforward" with useful features, especially for the final application. If the proposal could help the end-user's development experience, it could be fine I guess.

**Comment by sio4** [comment]
No update, so I am going to close this issue for now. Please feel free to reopen it anytime if you want to discuss it more.
