### ISSUE TITLE
License for envy is missing

### ISSUE THREAD

**Issue by toddy15** [gobuffalo/envy#6]
Hi,

I'd like to create a package of envy for Debian. However, I cannot proceed because the code does not have a license, neither in the source code comments nor as a separate file. As it stands, Debian would not be permitted to distribute your code.

I assume from your other repositories that the license is intended to be MIT, but could you clarify this for me, please? Ideally you could just include the file LICENSE.txt.

Regards,
Tobias

**Comment by markbates** [comment]
It’s MIT, and I’ll add one shortly. Sorry about that.
